# Generated by Django 3.1.4 on 2020-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='games',
            field=models.ManyToManyField(to='gaming.Game'),
        ),
    ]
